# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "SSH key added"
          chmod 600 ~/.ssh/id_rsa
          echo "key permission set to 600"
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SERVER_URL }} >> ~/.ssh/known_hosts
          echo "host added to known hosts"

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SERVER_URL }} -p ${{ secrets.SSH_PORT }} "echo $(date -Is) Hello World! >> hello.txt"